FROM node_base:1.0.0

# Setup for k3s

RUN echo "agent" > /etc/hostname

EXPOSE 6443:6443/tcp
EXPOSE 8472:8472/udp

# RUN ./k3s agent --server http://localhost:6443 --token ${NODE_TOKEN}
CMD ./k3s agent --server https://k3s.example.com --token ${NODE_TOKEN} -write-kubeconfig-mode=644

