services:

  node_base:
    build:
      dockerfile: Dockerfile.base
      args:
       NODE_TOKEN: nlhmcq.oxxnj9xav270vvz3
    image: node_base:1.0.0

  k3s_server:
    user: root
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.server
      # args:
      #  NODE_TOKEN: nlhmcq.oxxnj9xav270vvz3
    ports:
      - 6443:6443
      - 8472:8472
    volumes:
      - server:/server
    depends_on: 
       - node_base
  
  k3s_worker:
    depends_on: 
      - k3s_server
    build: 
      dockerfile: Dockerfile.agent
    ports:
      - 6443-6450:6443
      - 8472-8480:8472
    deploy:
      mode: replicated
      replicas: 1

    volumes:
      - agent:/agent

volumes:
  server: 
  agent:
